apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-msmk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0067-tenant/tkrw-pr712-0075-0067-app/devfile-sample-msmk@sha256:02dc99fa4a9b75ff930767530b8bc219bd54d60fdec4a0c725c7477929754833
        name: my-nodejs
        resources: {}
status: {}
